[versions]
agp = "8.6.1"
kotlin = "2.0.21"
lint = "27.2.2" # NOTE - this is quite old - need Kotlin version updated to 1.9 though to use later versions
mockk = "1.13.13"

[libraries]
android-gradle = { module = "com.android.tools.build:gradle", version.ref = "agp" }
androidx-annotations = "androidx.annotation:annotation:1.3.0"
app-androidx-core = "androidx.core:core-ktx:1.7.0"
app-androidx-appcompat = "androidx.appcompat:appcompat:1.5.1"
app-androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
app-androidx-fragment = "androidx.fragment:fragment-ktx:1.6.0"
app-androidx-lifecycle-viewmodel = "androidx.lifecycle:lifecycle-viewmodel-ktx:2.2.0"
app-material = "com.google.android.material:material:1.7.0"
eclipse-jgit = "org.eclipse.jgit:org.eclipse.jgit:6.10.0.202406032230-r"
kotlin-gradle-jvm = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
lint-api = { module = "com.android.tools.lint:lint-api", version.ref = "lint" }
lint-tests = { module = "com.android.tools.lint:lint-tests", version.ref = "lint" }
test-androidx-core = "androidx.test:core-ktx:1.6.1"
test-androidx-junit = "androidx.test.ext:junit:1.2.1"
test-androidx-runner = "androidx.test:runner:1.6.2"
test-kotlinx-coroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.8.0"
test-junit = "junit:junit:4.13.2"
test-mockk-jvm = { module = "io.mockk:mockk", version.ref = "mockk" }
test-mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }
test-okhttp-webserver = "com.squareup.okhttp3:mockwebserver:4.3.1"
test-robolectric = "org.robolectric:robolectric:4.13"

[plugins]
android-application = { id = "com.android.application" }
android-library = { id = "com.android.library" }
android-lint = { id = "com.android.lint" }
java = { id = "java-library" }
kotlin-android = { id = "org.jetbrains.kotlin.android" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm" }
tealium-gradle = { id = "tealium-plugin" }
tealium-library = { id = "tealium-library" }
